"use strict";

/* Chess Atlas — temporal/world navigation. Non-chess ancient games route to
 * their dedicated lightweight page; chess-family rules stay on the main board.
 */
const ATLAS_WORLD = {
  worldId: "earth-main", timelineId: "history", region: "world",
  nodes: [
    { id:"ur", year:-2600, label:"Royal Game of Ur", description:"Mesopotamian race-game tradition; surviving boards precede the later cuneiform rules evidence.", games:["race"], historicalGame:null, boardGame:"ur" },
    { id:"senet", year:-2500, label:"Senet", description:"Ancient Egyptian board-game tradition. Exact play is reconstructed because no complete ancient rulebook survives.", games:["race"], historicalGame:null, boardGame:"senet" },
    { id:"punic-opening", year:-218, label:"Second Punic War", description:"Hannibal leaves Iberia and advances toward Italy.", games:["chess","civilisation","diplomacy"], historicalGame:null, campaign:{title:"Hannibal's Italian Campaign",sides:"Rome vs Carthage",status:"Campaign begins",chessWhite:"Rome",chessBlack:"Carthage"} },
    { id:"cannae", year:-216, label:"Battle of Cannae", description:"A major confrontation between Rome and Hannibal.", games:["chess","civilisation","diplomacy"], historicalGame:null, campaign:{title:"Cannae",sides:"Rome vs Carthage",status:"Conflict available for resolution",chessWhite:"Rome",chessBlack:"Carthage"} },
    { id:"chaturanga", year:600, label:"Chaturanga", description:"Early Indian chess tradition.", games:["chess","civilisation"], historicalGame:"chaturanga" },
    { id:"shatranj", year:800, label:"Shatranj", description:"Chess spreads through the Islamic world.", games:["chess","civilisation","diplomacy"], historicalGame:"shatranj" },
    { id:"classical", year:1500, label:"Modern Chess Emerges", description:"European chess approaches its modern rules.", games:["chess","civilisation","diplomacy"], historicalGame:"modern" },
    { id:"industrial", year:1800, label:"Industrial World", description:"Population, industry and interstate competition accelerate.", games:["chess","civilisation","diplomacy"], historicalGame:"modern" },
    { id:"present", year:2026, label:"Present", description:"Observed history reaches the simulation boundary.", games:["chess","civilisation","diplomacy"], historicalGame:"modern" },
    { id:"near-future", year:2050, label:"Modelled Future", description:"Population and political trajectories become simulations.", games:["chess","civilisation","diplomacy","infinite"], historicalGame:"modern" },
    { id:"far-future", year:2200, label:"Speculative Future", description:"Tesseract, Infinite, timeline and quantum variants branch beyond historical chess.", games:["civilisation","diplomacy","infinite","4d","5d","quantum"], historicalGame:null, futureGames:true }
  ]
};

let currentNodeIndex=ATLAS_WORLD.nodes.findIndex(node=>node.id==="present");
let currentMode="chess", atlasMap=null, atlasMapError=null, manualGameExploration=false, applyingTimelineGame=false;
const HISTORICAL_GAME_LABELS={chaturanga:"Chaturanga",shatranj:"Shatranj",acedrex:"Acedrex — Spain 1283",modern:"Modern Chess"};
const getCurrentNode=()=>ATLAS_WORLD.nodes[currentNodeIndex];
const formatYear=year=>year<0?`${Math.abs(year)} BCE`:`${year} CE`;

function updateGameVariantContext(){const node=getCurrentNode(),context=document.getElementById("game-variant-context"),select=document.getElementById("game-variant"),game=node.historicalGame;if(manualGameExploration){const selected=HISTORICAL_GAME_LABELS[select.value]||"selected ruleset";context.textContent=game?`Manual exploration · timeline default: ${HISTORICAL_GAME_LABELS[game]}`:`Manual exploration · no historical chess-family game at ${formatYear(node.year)}`;select.setAttribute("aria-label",`${selected}. ${context.textContent}`);return;}context.textContent=game?`Timeline default · ${HISTORICAL_GAME_LABELS[game]}`:`Unavailable · no chess-family game at ${formatYear(node.year)}`;select.setAttribute("aria-label",context.textContent);}
function applyTimelineGame(){const node=getCurrentNode(),select=document.getElementById("game-variant");manualGameExploration=false;select.value=node.historicalGame||"";if(node.historicalGame){applyingTimelineGame=true;select.dispatchEvent(new Event("change",{bubbles:true}));applyingTimelineGame=false;}updateGameVariantContext();}
function selectManualGame(){if(applyingTimelineGame)return;manualGameExploration=true;updateGameVariantContext();renderMode();}
function ensureCampaignPanel(){if(document.getElementById("campaign-panel"))return;const panel=document.createElement("section");panel.id="campaign-panel";panel.className="campaign-panel";panel.hidden=true;panel.innerHTML=`<small>ACTIVE CAMPAIGN</small><h2 id="campaign-title"></h2><p id="campaign-sides"></p><p id="campaign-status"></p><div class="campaign-actions"><button id="resolve-history">▶ Historical outcome</button></div><p id="campaign-result"></p>`;const gameSpace=document.getElementById("game-space");gameSpace.parentNode.insertBefore(panel,gameSpace);document.getElementById("resolve-history").addEventListener("click",resolveHistorically);}
function renderCampaign(){const node=getCurrentNode(),panel=document.getElementById("campaign-panel");if(!node.campaign||currentMode!=="diplomacy"){panel.hidden=true;return;}panel.hidden=false;document.getElementById("campaign-title").textContent=node.campaign.title;document.getElementById("campaign-sides").textContent=node.campaign.sides;document.getElementById("campaign-status").textContent=node.campaign.status;document.getElementById("campaign-result").textContent="";}
function resolveHistorically(){const node=getCurrentNode();document.getElementById("campaign-result").textContent=node.id==="cannae"?"Historical path: Carthaginian victory at Cannae. The campaign continues rather than ending the war.":"Historical path selected. Advance the timeline to continue.";}
function setMode(mode){currentMode=mode;document.querySelectorAll(".atlas-mode[data-mode]").forEach(button=>button.classList.toggle("active",button.dataset.mode===currentMode));renderCampaign();renderMode();}
function moveTimeline(direction){const next=currentNodeIndex+direction;if(next<0||next>=ATLAS_WORLD.nodes.length)return;currentNodeIndex=next;renderTimeline();applyTimelineGame();renderCampaign();renderMode();}
function renderTimeline(){const node=getCurrentNode();document.getElementById("atlas-year").textContent=formatYear(node.year);document.getElementById("atlas-period").textContent=node.label;document.getElementById("atlas-description").textContent=node.description;document.getElementById("timeline-up").disabled=currentNodeIndex===ATLAS_WORLD.nodes.length-1;document.getElementById("timeline-down").disabled=currentNodeIndex===0;}
function renderMode(){const node=getCurrentNode(),board=document.getElementById("board"),controls=document.getElementById("chess-controls"),world=document.getElementById("world-panel"),variant=document.querySelector(".variant-control"),states=document.querySelector(".state-controls");if(currentMode==="chess"){const available=Boolean(node.historicalGame),show=available||manualGameExploration;variant.hidden=false;board.hidden=!show;controls.hidden=false;states.hidden=!show;world.hidden=true;if(!show){const status=document.getElementById("status");if(node.boardGame){status.innerHTML=`${node.label} is available in the ancient-games board. <a href="historical-play.html?game=${node.boardGame}">Play ${node.label} →</a>`;}else if(node.futureGames){status.innerHTML=`Future chess branches from this node. <a href="advanced-play.html">Open Future Chess →</a>`;}else status.textContent=`No historically valid chess-family game is available at ${formatYear(node.year)}. Choose a ruleset above only for manual exploration.`;}return;}variant.hidden=true;board.hidden=true;controls.hidden=true;states.hidden=true;world.hidden=false;const available=node.games.includes(currentMode),labels={diplomacy:"Diplomacy",civilisation:"Civilisation"},label=labels[currentMode]||currentMode;document.getElementById("world-mode-title").textContent=label;document.getElementById("world-mode-status").textContent=available?`${label} view — ${node.label}, ${formatYear(node.year)}`:`${label} is not yet available at this historical node.`;document.getElementById("world-mode-detail").textContent=available?`World: ${ATLAS_WORLD.worldId} · Timeline: ${ATLAS_WORLD.timelineId} · Region: ${ATLAS_WORLD.region}`:"The timeline remains fixed. Choose another representation or period.";if(atlasMapError)document.getElementById("world-mode-status").textContent=`The common world map could not load: ${atlasMapError.message}`;}
function initialiseAtlas(){ensureCampaignPanel();const viewport=document.getElementById("world-map"),summary=document.getElementById("world-map-summary");AtlasGeography.load("data/earth-main-v0.1.json").then(geography=>{atlasMap=new AtlasMapRenderer({viewport,geography,summary});document.getElementById("reset-world").addEventListener("click",()=>atlasMap.resetWorld());document.getElementById("focus-selection").addEventListener("click",()=>atlasMap.focusSelection());renderMode();}).catch(error=>{atlasMapError=error;summary.textContent="The Atlas world map is unavailable.";renderMode();});document.getElementById("timeline-up").addEventListener("click",()=>moveTimeline(1));document.getElementById("timeline-down").addEventListener("click",()=>moveTimeline(-1));document.querySelectorAll(".atlas-mode[data-mode]").forEach(button=>button.addEventListener("click",()=>setMode(button.dataset.mode)));document.getElementById("game-variant").addEventListener("change",selectManualGame);renderTimeline();applyTimelineGame();setMode("chess");}
document.addEventListener("DOMContentLoaded",initialiseAtlas);
