"use strict";
(()=>{
  const rules=window.JanggiRules,Module=window.ChessAtlasJanggiModule,Modules=window.ChessAtlasGameModules,Agents=window.ChessAtlasGameAgents,H=window.ChessAtlasAgentHeuristics,grid=document.getElementById('janggi-grid'),status=document.getElementById('janggi-status');
  if(!rules||!Module||!grid||!status)return;
  let state,selected=null,legal=[],busy=false;
  const sideName=s=>s==='cho'?'Cho':'Han',opponentMode=()=>document.getElementById('janggi-opponent').value,isAgentTurn=()=>state?.turn==='han'&&opponentMode()!=='human';
  function currentAgent(){const mode=opponentMode();if(mode==='heuristic')return H?.createAgent(Agents,'janggi',{id:'janggi-heuristic',name:'Atlas Heuristic'});if(mode==='random')return Agents?.randomAgent({id:'janggi-random',name:'Random Legal'});return null;}
  function render(){grid.textContent='';const keys=new Set(legal.map(([r,c])=>`${r},${c}`));for(let r=0;r<10;r++)for(let c=0;c<9;c++){const cell=document.createElement('button');cell.type='button';cell.className='janggi-point';cell.style.left=`${c/8*100}%`;cell.style.top=`${r/9*100}%`;const p=state.board[r][c];cell.setAttribute('aria-label',`row ${r+1}, column ${c+1}${p?', '+p.label:''}`);if(selected&&selected[0]===r&&selected[1]===c)cell.classList.add('selected');if(keys.has(`${r},${c}`))cell.classList.add('legal');if(p){const el=document.createElement('span');el.className=`janggi-piece ${p.side} type-${p.type}`;el.textContent=p.label;cell.appendChild(el);}cell.disabled=busy||isAgentTurn();cell.onclick=()=>choose(r,c);grid.appendChild(cell);}document.getElementById('janggi-pass').disabled=busy||isAgentTurn();}
  async function maybeAgent(){if(!isAgentTurn()||busy||!Modules||!Agents)return;const agent=currentAgent();if(!agent)return;busy=true;selected=null;legal=[];status.textContent='Han · agent thinking';render();try{const result=await Agents.takeTurn({modules:Modules,gameId:'janggi',game:state,agent});if(result.status==='applied'){state=result.result;status.textContent=`${sideName(state.turn)} to move${rules.isInCheck(state.board,state.turn)?' · check':''}`;}}catch(e){status.textContent=`Agent error: ${e.message}`;}finally{busy=false;render();}}
  function choose(r,c){if(busy||isAgentTurn())return;if(selected&&legal.some(([lr,lc])=>lr===r&&lc===c)){state=Module.applyAction(state,{type:'move',from:selected,to:[r,c]});selected=null;legal=[];status.textContent=`${sideName(state.turn)} to move${rules.isInCheck(state.board,state.turn)?' · check':''}`;render();void maybeAgent();return;}const p=state.board[r][c];if(p?.side===state.turn){selected=[r,c];legal=rules.legalMoves(state,selected);status.textContent=`${sideName(state.turn)} · ${p.label} selected · ${legal.length} legal move${legal.length===1?'':'s'}`;render();return;}selected=null;legal=[];status.textContent=`${sideName(state.turn)} to move · select one of your pieces`;render();}
  function reset(){const cho=document.getElementById('cho-formation').value,han=document.getElementById('han-formation').value;state=Module.create({choLayout:cho,hanLayout:han});selected=null;legal=[];busy=false;status.textContent='Cho to move';render();}
  document.getElementById('janggi-reset').onclick=reset;document.getElementById('cho-formation').onchange=reset;document.getElementById('han-formation').onchange=reset;document.getElementById('janggi-opponent').onchange=()=>{selected=null;legal=[];render();void maybeAgent();};document.getElementById('janggi-pass').onclick=()=>{if(busy||isAgentTurn())return;if(!rules.canPass(state)){status.textContent='Pass is not legal while in check';return;}state=Module.applyAction(state,{type:'pass'});selected=null;legal=[];status.textContent=`${sideName(state.turn)} to move · opponent passed`;render();void maybeAgent();};reset();
})();
