const J=require('./janggi-rules.js');

describe('Janggi lightweight legality core',()=>{
  test('Cho moves first and may pass when not in check',()=>{const s=J.initialState();expect(s.turn).toBe('cho');expect(J.canPass(s)).toBe(true);expect(J.pass(s).turn).toBe('han');});
  test('soldiers move forward or sideways but not backward',()=>{const s=J.initialState();expect(J.legalMove(s,[3,4],[4,4])).toBe(true);expect(J.legalMove(s,[3,4],[3,3])).toBe(true);expect(J.legalMove(s,[3,4],[2,4])).toBe(false);});
  test('horse is blocked on its orthogonal first step',()=>{const s=J.initialState();s.board=Array.from({length:10},()=>Array(9).fill(null));s.board[1][4]={side:'cho',type:'k',label:'楚'};s.board[8][4]={side:'han',type:'k',label:'漢'};s.board[4][4]={side:'cho',type:'h',label:'馬'};expect(J.legalMove(s,[4,4],[6,5])).toBe(true);s.board[5][4]={side:'cho',type:'p',label:'卒'};expect(J.legalMove(s,[4,4],[6,5])).toBe(false);});
  test('elephant uses one orthogonal then two diagonal steps and can be blocked',()=>{const s=J.initialState();s.board=Array.from({length:10},()=>Array(9).fill(null));s.board[1][4]={side:'cho',type:'k',label:'楚'};s.board[8][4]={side:'han',type:'k',label:'漢'};s.board[3][3]={side:'cho',type:'e',label:'象'};expect(J.legalMove(s,[3,3],[6,5])).toBe(true);s.board[4][3]={side:'han',type:'p',label:'兵'};expect(J.legalMove(s,[3,3],[6,5])).toBe(false);});
  test('cannon must jump exactly one non-cannon screen and cannot capture a cannon',()=>{const s=J.initialState();s.board=Array.from({length:10},()=>Array(9).fill(null));s.board[1][4]={side:'cho',type:'k',label:'楚'};s.board[8][4]={side:'han',type:'k',label:'漢'};s.board[4][0]={side:'cho',type:'c',label:'包'};s.board[4][2]={side:'cho',type:'p',label:'卒'};s.board[4][5]={side:'han',type:'r',label:'車'};expect(J.legalMove(s,[4,0],[4,5])).toBe(true);s.board[4][5]={side:'han',type:'c',label:'包'};expect(J.legalMove(s,[4,0],[4,5])).toBe(false);s.board[4][2]={side:'cho',type:'c',label:'包'};expect(J.legalMove(s,[4,0],[4,5])).toBe(false);});
  test('general and guard use palace diagonals but cannot leave palace',()=>{const s=J.initialState();expect(J.legalMove(s,[1,4],[0,3])).toBe(false);s.board[0][3]=null;expect(J.legalMove(s,[1,4],[0,3])).toBe(true);expect(J.legalMove(s,[1,4],[3,4])).toBe(false);});
});
